# Generated by Django 3.2 on 2022-04-19 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0002_sharingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingdetails',
            name='receiver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sharingdetails',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
